name: GameKnightz
favicon: null
layout_spectrum: 0.29831
typography_spectrum: 0.19287
title: Game Knightz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#251a15'
    - '#dca30c'
    - '#6a5746'
    - '#af7164'
    - '#f9ede3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.7188014884013683
  rhythmicContrast: 0.75
purpose: []
